### ISSUE TITLE
Ocurrio un error al procesar el pago

### ISSUE THREAD

**Issue by Masterfarias** [TodoPago/Plugin-PrestaShop#15]
Este es el error que me da cuando elijo Todo Pago como forma de pago:
![image](https://cloud.githubusercontent.com/assets/25466294/22509505/0c7e37b4-e86d-11e6-8119-f58843da83ba.png)

Utilizo Prestashop 1.6 y eh desecargado la ultima version de Todo Pago para esta version.

**Comment by drarko** [comment]
Estimado,
El modulo genera un log en modules/todopago/todopago.log, ¿podria adjuntarlo para revisar el error en detalle?
Gracias

**Comment by shacker2** [comment]
al seleccionar pago en cuotas, da este error (la transaccion se realiza pero no genera la orden en prestashop) en 1 pago no hay error

[2017-02-02T14:31:13-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2052 - Ord.19465) first step
[2017-02-02T14:31:13-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2052 - Ord.19465) EXCEPCION
exception 'Exception' with message 'second_step ya realizado' in /home/llameyac/public_html/modules/todopago/controllers/front/payment.php:165
Stack trace:
#0 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(240): TodoPagoPaymentModuleFrontController->prepare_order(Object(Cart))
#1 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/llameyac/public_html/classes/controller/Controller.php(180): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/llameyac/public_html/classes/Dispatcher.php(373): ControllerCore->run()
#4 /home/llameyac/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}
[2017-02-02T14:33:29-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) first step
[2017-02-02T14:33:29-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) params SAR - {"comercio":{"Security":"1DD32A282710DD185AB4BC91039997A2","EncodingMethod":"XML","Merchant":"13404","URL_OK":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=1&cart=22622","URL_ERROR":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=0&cart=22622"},"operacion":{"MERCHANT":"13404","OPERATIONID":"22622","CURRENCYCODE":"032","AMOUNT":3340,"MAXINSTALLMENTS":"6","CSBTCITY":"villa crespo","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":3363,"CSBTIPADDRESS":"181.88.184.26","CSBTEMAIL":"alejandroa@tevecompras.com","CSBTFIRSTNAME":"Alejandro","CSBTLASTNAME":"Avalo","CSBTPHONENUMBER":"54111555555555","CSBTPOSTALCODE":"1414","CSBTSTATE":"B","CSBTSTREET1":"av corrientes 4850","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"3340.00","CSMDD7":"251","CSMDD10":"0","CSMDD11":"54111555555555","CSMDD8":"N","CSMDD9":"03415bafd009ba6627ba7178a2b4fe7f","CSITPRODUCTCODE":"Inicio","CSITPRODUCTDESCRIPTION":"ETERNITY LUX ha tomado lo mejor de la cermica y de","CSITPRODUCTNAME":"Eternity Lux","CSITPRODUCTSKU":"367","CSITTOTALAMOUNT":"3340.00","CSITQUANTITY":"1","CSITUNITPRICE":"3340.00","CSSTCITY":"villa crespo","CSSTCOUNTRY":"AR","CSSTEMAIL":"alejandroa@tevecompras.com","CSSTFIRSTNAME":"Alejandro","CSSTLASTNAME":"Avalo","CSSTPHONENUMBER":"54111555555555","CSSTPOSTALCODE":"1414","CSSTSTATE":"B","CSSTSTREET1":"av corrientes 4850","CSMDD13":"OCA Env\u00edos","CSMDD12":"10","CSMDD16":""}}
[2017-02-02T14:33:30-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) response SAR - {"StatusCode":-1,"StatusMessage":"Solicitud de Autorizacion Registrada","URL_Request":"https:\/\/forms.todopago.com.ar\/formulario\/commands?command=formulario&m=t0992d0fe-77a0-35e6-d421-34c5b1b27d78","RequestKey":"84e65dec-e730-b22b-e204-19fb3e70487b","PublicRequestKey":"t0992d0fe-77a0-35e6-d421-34c5b1b27d78"}
[2017-02-02T14:34:24-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) first step
[2017-02-02T14:34:24-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) params SAR - {"comercio":{"Security":"1DD32A282710DD185AB4BC91039997A2","EncodingMethod":"XML","Merchant":"13404","URL_OK":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=1&cart=22622","URL_ERROR":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=0&cart=22622"},"operacion":{"MERCHANT":"13404","OPERATIONID":"22622","CURRENCYCODE":"032","AMOUNT":2,"MAXINSTALLMENTS":"6","CSBTCITY":"villa crespo","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":3363,"CSBTIPADDRESS":"181.88.184.26","CSBTEMAIL":"alejandroa@tevecompras.com","CSBTFIRSTNAME":"Alejandro","CSBTLASTNAME":"Avalo","CSBTPHONENUMBER":"54111555555555","CSBTPOSTALCODE":"1414","CSBTSTATE":"B","CSBTSTREET1":"av corrientes 4850","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"2.00","CSMDD7":"251","CSMDD10":"0","CSMDD11":"54111555555555","CSMDD8":"N","CSMDD9":"03415bafd009ba6627ba7178a2b4fe7f","CSITPRODUCTCODE":"Root","CSITPRODUCTDESCRIPTION":"prueba","CSITPRODUCTNAME":"Producto de prueba","CSITPRODUCTSKU":"319","CSITTOTALAMOUNT":"2.00","CSITQUANTITY":"1","CSITUNITPRICE":"2.00","CSSTCITY":"villa crespo","CSSTCOUNTRY":"AR","CSSTEMAIL":"alejandroa@tevecompras.com","CSSTFIRSTNAME":"Alejandro","CSSTLASTNAME":"Avalo","CSSTPHONENUMBER":"54111555555555","CSSTPOSTALCODE":"1414","CSSTSTATE":"B","CSSTSTREET1":"av corrientes 4850","CSMDD13":"OCA Env\u00edos","CSMDD12":"10","CSMDD16":""}}
[2017-02-02T14:34:25-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) response SAR - {"StatusCode":-1,"StatusMessage":"Solicitud de Autorizacion Registrada","URL_Request":"https:\/\/forms.todopago.com.ar\/formulario\/commands?command=formulario&m=t62bdc6e1-1ec2-197f-bbbc-dbd68d7515b6","RequestKey":"41464945-594e-0dd3-b39b-6012fa71b256","PublicRequestKey":"t62bdc6e1-1ec2-197f-bbbc-dbd68d7515b6"}
[2017-02-02T14:35:19-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) first step
[2017-02-02T14:35:19-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) params SAR - {"comercio":{"Security":"1DD32A282710DD185AB4BC91039997A2","EncodingMethod":"XML","Merchant":"13404","URL_OK":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=1&cart=22705","URL_ERROR":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=0&cart=22705"},"operacion":{"MERCHANT":"13404","OPERATIONID":"22705","CURRENCYCODE":"032","AMOUNT":2,"MAXINSTALLMENTS":"6","CSBTCITY":"capital","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":8229,"CSBTIPADDRESS":"186.23.203.143","CSBTEMAIL":"test@dada.com","CSBTFIRSTNAME":"Fds","CSBTLASTNAME":"fdsf","CSBTPHONENUMBER":"541163790204","CSBTPOSTALCODE":"1444","CSBTSTATE":"C","CSBTSTREET1":"pola 1234","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"2.00","CSMDD7":"0","CSMDD10":"1","CSMDD11":"541163790204","CSMDD8":"N","CSMDD9":"b70efaa9432f15712524ce7f5a150b89","CSITPRODUCTCODE":"Root","CSITPRODUCTDESCRIPTION":"prueba","CSITPRODUCTNAME":"Producto de prueba","CSITPRODUCTSKU":"319","CSITTOTALAMOUNT":"2.00","CSITQUANTITY":"1","CSITUNITPRICE":"2.00","CSSTCITY":"capital","CSSTCOUNTRY":"AR","CSSTEMAIL":"test@dada.com","CSSTFIRSTNAME":"Fds","CSSTLASTNAME":"fdsf","CSSTPHONENUMBER":"541163790204","CSSTPOSTALCODE":"1444","CSSTSTATE":"C","CSSTSTREET1":"pola 1234","CSMDD13":"Retiro en Casa Central","CSMDD12":"10","CSMDD16":""}}
[2017-02-02T14:35:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) response SAR - {"StatusCode":-1,"StatusMessage":"Solicitud de Autorizacion Registrada","URL_Request":"https:\/\/forms.todopago.com.ar\/formulario\/commands?command=formulario&m=t096eff8c-ddc0-d6c0-9c69-9045ea5ff586","RequestKey":"35e2dd1e-9ab6-2086-24ae-8cdba9c58f3a","PublicRequestKey":"t096eff8c-ddc0-d6c0-9c69-9045ea5ff586"}
[2017-02-02T14:35:47-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) second step
[2017-02-02T14:35:47-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) params GAA - {"Merchant":"13404","MERCHANT":"13404","Security":"1DD32A282710DD185AB4BC91039997A2","AnswerKey":"91ec1900-1259-def7-0188-232941b10e2c","RequestKey":"41464945-594e-0dd3-b39b-6012fa71b256"}
[2017-02-02T14:35:48-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) response GAA - {"StatusCode":-1,"StatusMessage":"APROBADA","AuthorizationKey":"62b5105a-5145-3390-d480-60aebee6deeb","EncodingMethod":"XML","Payload":{"Answer":{"DATETIME":"2017-02-02T14:35:29Z","CURRENCYNAME":"Peso Argentino","PAYMENTMETHODNAME":"AMEX","TICKETNUMBER":"9186","AUTHORIZATIONCODE":"270000","CARDNUMBERVISIBLE":"37779003XXXXX9803","BARCODE":"","OPERATIONID":"22622","COUPONEXPDATE":"","COUPONSECEXPDATE":"","COUPONSUBSCRIBER":"","BARCODETYPE":"","ASSOCIATEDDOCUMENTATION":"","INSTALLMENTPAYMENTS":"3"},"Request":{"MERCHANT":"13404","OPERATIONID":"22622","AMOUNT":"2.05","CURRENCYCODE":"32","AMOUNTBUYER":"2.05","BANKID":"18","PROMOTIONID":"1479446"}}}
[2017-02-02T14:35:48-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.3363 - Ord.22622) EXCEPCION
exception 'Exception' with message 'APROBADA' in /home/llameyac/public_html/modules/todopago/controllers/front/payment.php:319
Stack trace:
#0 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(341): TodoPagoPaymentModuleFrontController->take_action(Array)
#1 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(95): TodoPagoPaymentModuleFrontController->second_step_todopago('TODOPAGO_PRODUC...', Object(Cart), Object(TodoPago\Sdk))
#2 /home/llameyac/public_html/classes/controller/Controller.php(180): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/llameyac/public_html/classes/Dispatcher.php(373): ControllerCore->run()
#4 /home/llameyac/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}
[2017-02-02T14:36:14-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) second step
[2017-02-02T14:36:14-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) params GAA - {"Merchant":"13404","MERCHANT":"13404","Security":"1DD32A282710DD185AB4BC91039997A2","AnswerKey":"7558f0a4-79fa-43eb-378d-e872348b6453","RequestKey":"35e2dd1e-9ab6-2086-24ae-8cdba9c58f3a"}
[2017-02-02T14:36:15-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) response GAA - {"StatusCode":-1,"StatusMessage":"APROBADA","AuthorizationKey":"7497d2e0-5ba2-4209-bfa0-997613ee395f","EncodingMethod":"XML","Payload":{"Answer":{"DATETIME":"2017-02-02T14:35:55Z","CURRENCYNAME":"Peso Argentino","PAYMENTMETHODNAME":"VISA","TICKETNUMBER":"6892","AUTHORIZATIONCODE":"004941","CARDNUMBERVISIBLE":"45407300XXXXXX6351","BARCODE":"","OPERATIONID":"22705","COUPONEXPDATE":"","COUPONSECEXPDATE":"","COUPONSUBSCRIBER":"","BARCODETYPE":"","ASSOCIATEDDOCUMENTATION":"","INSTALLMENTPAYMENTS":"1"},"Request":{"MERCHANT":"13404","OPERATIONID":"22705","AMOUNT":"2.00","CURRENCYCODE":"32","AMOUNTBUYER":"2.00","BANKID":"7","PROMOTIONID":"1479492"}}}
[2017-02-02T14:36:15-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) Redireccionando al controller de validacion
[2017-02-02T14:36:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) Creada orden id 3178 para carro id 22705
[2017-02-02T14:36:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22705) Status: {"DATETIME":"2017-02-02T14:35:55Z","CURRENCYNAME":"Peso Argentino","PAYMENTMETHODNAME":"VISA","TICKETNUMBER":"6892","AUTHORIZATIONCODE":"004941","CARDNUMBERVISIBLE":"45407300XXXXXX6351","BARCODE":"","OPERATIONID":"22705","COUPONEXPDATE":"","COUPONSECEXPDATE":"","COUPONSUBSCRIBER":"","BARCODETYPE":"","ASSOCIATEDDOCUMENTATION":"","INSTALLMENTPAYMENTS":"1"}
[2017-02-02T14:39:51-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) first step
[2017-02-02T14:39:52-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) params SAR - {"comercio":{"Security":"1DD32A282710DD185AB4BC91039997A2","EncodingMethod":"XML","Merchant":"13404","URL_OK":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=1&cart=22707","URL_ERROR":"https:\/\/tevecompras.com\/module\/todopago\/payment?paso=2&estado=0&cart=22707"},"operacion":{"MERCHANT":"13404","OPERATIONID":"22707","CURRENCYCODE":"032","AMOUNT":2,"MAXINSTALLMENTS":"6","CSBTCITY":"capital","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":8229,"CSBTIPADDRESS":"186.23.203.143","CSBTEMAIL":"test@dada.com","CSBTFIRSTNAME":"Fds","CSBTLASTNAME":"fdsf","CSBTPHONENUMBER":"541163790204","CSBTPOSTALCODE":"1444","CSBTSTATE":"C","CSBTSTREET1":"pola 1234","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"2.00","CSMDD7":"0","CSMDD10":"2","CSMDD11":"541163790204","CSMDD8":"N","CSMDD9":"b70efaa9432f15712524ce7f5a150b89","CSITPRODUCTCODE":"Root","CSITPRODUCTDESCRIPTION":"prueba","CSITPRODUCTNAME":"Producto de prueba","CSITPRODUCTSKU":"319","CSITTOTALAMOUNT":"2.00","CSITQUANTITY":"1","CSITUNITPRICE":"2.00","CSSTCITY":"capital","CSSTCOUNTRY":"AR","CSSTEMAIL":"test@dada.com","CSSTFIRSTNAME":"Fds","CSSTLASTNAME":"fdsf","CSSTPHONENUMBER":"541163790204","CSSTPOSTALCODE":"1444","CSSTSTATE":"C","CSSTSTREET1":"pola 1234","CSMDD13":"Retiro en Casa Central","CSMDD12":"10","CSMDD16":""}}
[2017-02-02T14:39:52-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) response SAR - {"StatusCode":-1,"StatusMessage":"Solicitud de Autorizacion Registrada","URL_Request":"https:\/\/forms.todopago.com.ar\/formulario\/commands?command=formulario&m=tca939c21-b92f-88e0-3829-d039a1da3494","RequestKey":"78fe463f-7b35-8328-cccf-52f90d0a7b1a","PublicRequestKey":"tca939c21-b92f-88e0-3829-d039a1da3494"}
[2017-02-02T14:40:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) second step
[2017-02-02T14:40:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) params GAA - {"Merchant":"13404","MERCHANT":"13404","Security":"1DD32A282710DD185AB4BC91039997A2","AnswerKey":"74035e4e-411d-1824-363b-1d5f47b0a070","RequestKey":"78fe463f-7b35-8328-cccf-52f90d0a7b1a"}
[2017-02-02T14:40:44-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) response GAA - {"StatusCode":-1,"StatusMessage":"APROBADA","AuthorizationKey":"c28c0610-5676-92af-211b-22e1a0e8a133","EncodingMethod":"XML","Payload":{"Answer":{"DATETIME":"2017-02-02T14:40:24Z","CURRENCYNAME":"Peso Argentino","PAYMENTMETHODNAME":"VISA","TICKETNUMBER":"2312","AUTHORIZATIONCODE":"001848","CARDNUMBERVISIBLE":"45407300XXXXXX6351","BARCODE":"","OPERATIONID":"22707","COUPONEXPDATE":"","COUPONSECEXPDATE":"","COUPONSUBSCRIBER":"","BARCODETYPE":"","ASSOCIATEDDOCUMENTATION":"","INSTALLMENTPAYMENTS":"3"},"Request":{"MERCHANT":"13404","OPERATIONID":"22707","AMOUNT":"2.05","CURRENCYCODE":"32","AMOUNTBUYER":"2.05","BANKID":"7","PROMOTIONID":"1479494"}}}
[2017-02-02T14:40:44-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) EXCEPCION
exception 'Exception' with message 'APROBADA' in /home/llameyac/public_html/modules/todopago/controllers/front/payment.php:319
Stack trace:
#0 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(341): TodoPagoPaymentModuleFrontController->take_action(Array)
#1 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(95): TodoPagoPaymentModuleFrontController->second_step_todopago('TODOPAGO_PRODUC...', Object(Cart), Object(TodoPago\Sdk))
#2 /home/llameyac/public_html/classes/controller/Controller.php(180): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/llameyac/public_html/classes/Dispatcher.php(373): ControllerCore->run()
#4 /home/llameyac/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}

**Comment by drarko** [comment]
Por favor, probar con la ultima version recien publicada 1.8.2
Gracias
