### ISSUE TITLE
al actualizar a 1.8.2 y seleccionar todo pago da error

### ISSUE THREAD

**Issue by shacker2** [TodoPago/Plugin-PrestaShop#17]
con la ultima version da error al seleccionar todo pago

Ocurrio un error
Por favor intente nuevamente.

**Comment by shacker2** [comment]
adjunto log

[2017-02-02T16:08:34-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.2 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) first step
[2017-02-02T16:08:34-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.0.9 - Pv.1.8.2 - EP.TODOPAGO_ENDPOINT_PROD - Cus.8229 - Ord.22707) EXCEPCION
exception 'Exception' with message 'second_step ya realizado' in /home/llameyac/public_html/modules/todopago/controllers/front/payment.php:165
Stack trace:
#0 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(240): TodoPagoPaymentModuleFrontController->prepare_order(Object(Cart))
#1 /home/llameyac/public_html/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/llameyac/public_html/classes/controller/Controller.php(180): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/llameyac/public_html/classes/Dispatcher.php(373): ControllerCore->run()
#4 /home/llameyac/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}
