### ISSUE TITLE
Presta 1.7

### ISSUE THREAD

**Issue by dariodipa** [TodoPago/Plugin-PrestaShop#19]
Tanto con la activacion o no del formulario hibrido, al momento del pago.

> Ocurrio un error
> Por favor intente nuevamente.

**Comment by drarko** [comment]
Por favor adjuntar el log que se genera en modules/todopago/todopago.log

**Comment by dariodipa** [comment]
[2017-03-16T11:22:05-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) Redireccionando al paso 1
[2017-03-16T11:22:05-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) first step
[2017-03-16T11:22:05-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) params SAR - {"comercio":{"Security":"cec652c1b80e449fbcb5d2467b626df6","EncodingMethod":"XML","Merchant":"17882","URL_OK":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=1&cart=1&fc=module&module=todopago&controller=payment","URL_ERROR":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=0&cart=1&fc=module&module=todopago&controller=payment"},"operacion":{"MERCHANT":"17882","OPERATIONID":"1","CURRENCYCODE":"032","AMOUNT":811.5,"MAXINSTALLMENTS":"6","CSBTCITY":"Gualeguay","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":1,"CSBTIPADDRESS":"190.194.43.137","CSBTEMAIL":"dariodipa@gmail.com","CSBTFIRSTNAME":"Dario","CSBTLASTNAME":"Di Paolo","CSBTPHONENUMBER":"54","CSBTPOSTALCODE":"2840","CSBTSTATE":"E","CSBTSTREET1":"La Rioja 4051","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"811.50","CSMDD7":"15","CSMDD10":"0","CSMDD11":"54","CSMDD8":"N","CSMDD9":"$2y$10$8Fh43WnJliINgKebQLkv4OH9oxjz9dmaVumwrl2ImkPzxyGbsOP8S","CSITPRODUCTCODE":"Inicio#Inicio","CSITPRODUCTDESCRIPTION":"Touchscreen  MTCTP-211A - Consultar Color#Touchscreen QSD E-C7119-01  - Consultar Color","CSITPRODUCTNAME":"Touchscreen  MTCTP-211A#Touchscreen QSD E-C7119-01","CSITPRODUCTSKU":"300#18","CSITTOTALAMOUNT":"331.50#480.00","CSITQUANTITY":"1#1","CSITUNITPRICE":"331.50#480.00","CSSTCITY":"Gualeguay","CSSTCOUNTRY":"AR","CSSTEMAIL":"dariodipa@gmail.com","CSSTFIRSTNAME":"Dario","CSSTLASTNAME":"Di Paolo","CSSTPHONENUMBER":"54","CSSTPOSTALCODE":"2840","CSSTSTATE":"E","CSSTSTREET1":"La Rioja 4051","CSMDD13":"Di Paolo Distribuciones","CSMDD12":"30","CSMDD16":""}}
[2017-03-16T11:22:07-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) response SAR - {"StatusCode":98108,"StatusMessage":"Verifique el formato del campo numero telefono de los datos de facturaci\u00f3n."}
[2017-03-16T11:22:07-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) EXCEPCION
Exception: Verifique el formato del campo numero telefono de los datos de facturación. in /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php:227
Stack trace:
#0 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(274): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/dipa/dipa.com.ar/classes/controller/Controller.php(201): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/dipa/dipa.com.ar/classes/Dispatcher.php(366): ControllerCore->run()
#4 /home/dipa/dipa.com.ar/index.php(28): DispatcherCore->dispatch()
#5 {main}
[2017-03-16T11:23:03-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) Redireccionando al paso 1
[2017-03-16T11:23:03-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) first step
[2017-03-16T11:23:03-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) params SAR - {"comercio":{"Security":"cec652c1b80e449fbcb5d2467b626df6","EncodingMethod":"XML","Merchant":"17882","URL_OK":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=1&cart=1&fc=module&module=todopago&controller=payment","URL_ERROR":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=0&cart=1&fc=module&module=todopago&controller=payment"},"operacion":{"MERCHANT":"17882","OPERATIONID":"1","CURRENCYCODE":"032","AMOUNT":811.5,"MAXINSTALLMENTS":"6","CSBTCITY":"Gualeguay","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":1,"CSBTIPADDRESS":"190.194.43.137","CSBTEMAIL":"dariodipa@gmail.com","CSBTFIRSTNAME":"Dario","CSBTLASTNAME":"Di Paolo","CSBTPHONENUMBER":"54","CSBTPOSTALCODE":"2840","CSBTSTATE":"E","CSBTSTREET1":"La Rioja 4051","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"811.50","CSMDD7":"15","CSMDD10":"0","CSMDD11":"54","CSMDD8":"N","CSMDD9":"$2y$10$8Fh43WnJliINgKebQLkv4OH9oxjz9dmaVumwrl2ImkPzxyGbsOP8S","CSITPRODUCTCODE":"Inicio#Inicio","CSITPRODUCTDESCRIPTION":"Touchscreen  MTCTP-211A - Consultar Color#Touchscreen QSD E-C7119-01  - Consultar Color","CSITPRODUCTNAME":"Touchscreen  MTCTP-211A#Touchscreen QSD E-C7119-01","CSITPRODUCTSKU":"300#18","CSITTOTALAMOUNT":"331.50#480.00","CSITQUANTITY":"1#1","CSITUNITPRICE":"331.50#480.00","CSSTCITY":"Gualeguay","CSSTCOUNTRY":"AR","CSSTEMAIL":"dariodipa@gmail.com","CSSTFIRSTNAME":"Dario","CSSTLASTNAME":"Di Paolo","CSSTPHONENUMBER":"54","CSSTPOSTALCODE":"2840","CSSTSTATE":"E","CSSTSTREET1":"La Rioja 4051","CSMDD13":"Di Paolo Distribuciones","CSMDD12":"30","CSMDD16":""}}
[2017-03-16T11:23:05-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) response SAR - {"StatusCode":98108,"StatusMessage":"Verifique el formato del campo numero telefono de los datos de facturaci\u00f3n."}
[2017-03-16T11:23:05-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) EXCEPCION
Exception: Verifique el formato del campo numero telefono de los datos de facturación. in /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php:227
Stack trace:
#0 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(274): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/dipa/dipa.com.ar/classes/controller/Controller.php(201): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/dipa/dipa.com.ar/classes/Dispatcher.php(366): ControllerCore->run()
#4 /home/dipa/dipa.com.ar/index.php(28): DispatcherCore->dispatch()
#5 {main}
[2017-03-16T11:23:45-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) Redireccionando al paso 1
[2017-03-16T11:23:45-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) first step
[2017-03-16T11:23:45-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) params SAR - {"comercio":{"Security":"cec652c1b80e449fbcb5d2467b626df6","EncodingMethod":"XML","Merchant":"17882","URL_OK":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=1&cart=1&fc=module&module=todopago&controller=payment","URL_ERROR":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=0&cart=1&fc=module&module=todopago&controller=payment"},"operacion":{"MERCHANT":"17882","OPERATIONID":"1","CURRENCYCODE":"032","AMOUNT":811.5,"MAXINSTALLMENTS":"6","CSBTCITY":"Gualeguay","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":1,"CSBTIPADDRESS":"190.194.43.137","CSBTEMAIL":"dariodipa@gmail.com","CSBTFIRSTNAME":"Dario","CSBTLASTNAME":"Di Paolo","CSBTPHONENUMBER":"54","CSBTPOSTALCODE":"2840","CSBTSTATE":"E","CSBTSTREET1":"La Rioja 4051","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"811.50","CSMDD7":"15","CSMDD10":"0","CSMDD11":"54","CSMDD8":"N","CSMDD9":"$2y$10$8Fh43WnJliINgKebQLkv4OH9oxjz9dmaVumwrl2ImkPzxyGbsOP8S","CSITPRODUCTCODE":"Inicio#Inicio","CSITPRODUCTDESCRIPTION":"Touchscreen  MTCTP-211A - Consultar Color#Touchscreen QSD E-C7119-01  - Consultar Color","CSITPRODUCTNAME":"Touchscreen  MTCTP-211A#Touchscreen QSD E-C7119-01","CSITPRODUCTSKU":"300#18","CSITTOTALAMOUNT":"331.50#480.00","CSITQUANTITY":"1#1","CSITUNITPRICE":"331.50#480.00","CSSTCITY":"Gualeguay","CSSTCOUNTRY":"AR","CSSTEMAIL":"dariodipa@gmail.com","CSSTFIRSTNAME":"Dario","CSSTLASTNAME":"Di Paolo","CSSTPHONENUMBER":"54","CSSTPOSTALCODE":"2840","CSSTSTATE":"E","CSSTSTREET1":"La Rioja 4051","CSMDD13":"Di Paolo Distribuciones","CSMDD12":"30","CSMDD16":""}}
[2017-03-16T11:23:46-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) response SAR - {"StatusCode":98108,"StatusMessage":"Verifique el formato del campo numero telefono de los datos de facturaci\u00f3n."}
[2017-03-16T11:23:46-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) EXCEPCION
Exception: Verifique el formato del campo numero telefono de los datos de facturación. in /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php:227
Stack trace:
#0 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(274): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/dipa/dipa.com.ar/classes/controller/Controller.php(201): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/dipa/dipa.com.ar/classes/Dispatcher.php(366): ControllerCore->run()
#4 /home/dipa/dipa.com.ar/index.php(28): DispatcherCore->dispatch()
#5 {main}
[2017-03-16T11:57:14-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) Redireccionando al paso 1
[2017-03-16T11:57:15-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) first step
[2017-03-16T11:57:15-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) params SAR - {"comercio":{"Security":"cec652c1b80e449fbcb5d2467b626df6","EncodingMethod":"XML","Merchant":"17882","URL_OK":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=1&cart=1&fc=module&module=todopago&controller=payment","URL_ERROR":"https:\/\/www.dipa.com.ar\/index.php?paso=2&estado=0&cart=1&fc=module&module=todopago&controller=payment"},"operacion":{"MERCHANT":"17882","OPERATIONID":"1","CURRENCYCODE":"032","AMOUNT":811.5,"MAXINSTALLMENTS":"6","CSBTCITY":"Gualeguay","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":1,"CSBTIPADDRESS":"190.194.43.137","CSBTEMAIL":"dariodipa@gmail.com","CSBTFIRSTNAME":"Dario","CSBTLASTNAME":"Di Paolo","CSBTPHONENUMBER":"54","CSBTPOSTALCODE":"2840","CSBTSTATE":"E","CSBTSTREET1":"La Rioja 4051","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"811.50","CSMDD7":"15","CSMDD10":"0","CSMDD11":"54","CSMDD8":"N","CSMDD9":"$2y$10$8Fh43WnJliINgKebQLkv4OH9oxjz9dmaVumwrl2ImkPzxyGbsOP8S","CSITPRODUCTCODE":"Inicio#Inicio","CSITPRODUCTDESCRIPTION":"Touchscreen  MTCTP-211A - Consultar Color#Touchscreen QSD E-C7119-01  - Consultar Color","CSITPRODUCTNAME":"Touchscreen  MTCTP-211A#Touchscreen QSD E-C7119-01","CSITPRODUCTSKU":"300#18","CSITTOTALAMOUNT":"331.50#480.00","CSITQUANTITY":"1#1","CSITUNITPRICE":"331.50#480.00","CSSTCITY":"Gualeguay","CSSTCOUNTRY":"AR","CSSTEMAIL":"dariodipa@gmail.com","CSSTFIRSTNAME":"Dario","CSSTLASTNAME":"Di Paolo","CSSTPHONENUMBER":"54","CSSTPOSTALCODE":"2840","CSSTSTATE":"E","CSSTSTREET1":"La Rioja 4051","CSMDD13":"Di Paolo Distribuciones","CSMDD12":"30","CSMDD16":""}}
[2017-03-16T11:57:57-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) response SAR - {"StatusCode":98108,"StatusMessage":"Verifique el formato del campo numero telefono de los datos de facturaci\u00f3n."}
[2017-03-16T11:57:57-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.14 - eCv.1.7.0.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.1 - Ord.1) EXCEPCION
Exception: Verifique el formato del campo numero telefono de los datos de facturación. in /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php:227
Stack trace:
#0 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(274): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/dipa/dipa.com.ar/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/dipa/dipa.com.ar/classes/controller/Controller.php(201): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/dipa/dipa.com.ar/classes/Dispatcher.php(366): ControllerCore->run()
#4 /home/dipa/dipa.com.ar/index.php(28): DispatcherCore->dispatch()
#5 {main}

**Comment by dariodipa** [comment]
Mauricio, los campos de datos personales del usuario en mi web, estaba como opcional el telefono y el campo vacio, lo voy a pasar a obligatorio, anda todo perfecto, Muchas gracias.

**Comment by drarko** [comment]
Pefecto! Reabrir en caso de ser necesario
Saludos
