### ISSUE TITLE
Error al pagar

### ISSUE THREAD

**Issue by sebadixon** [TodoPago/Plugin-PrestaShop#45]
# PrestaShop-plugin | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [x ] ¿Habilitaste la extensión SOAP de PHP?
* [x ] ¿Habilitaste la extensión CURL de PHP?
* [ x] ¿Habilitaste la extensión openSSL de PHP?
* [x ] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [ ] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento actual
> al hacer click sobre el botón de Todo Pago para pagar, salta a la página "Ocurrió un Error" y el botón elegir otro método de pago, o sea, no es del tipo de página "error 404", sino que sigue dentro de la tienda de prestashop.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP: 7.1
  * __Versión de PrestaShop: 1.6
  * __Versión de TodoPago: 1.15.0
  * __Ambiente de Todopago: producción

**Comment by curcio79** [comment]
@sebadixon buenos dias, tenes la pagina en online para verificar? o sino podrias enviarme los logs? 
Saludos

**Comment by sebadixon** [comment]
> @sebadixon buenos dias, tenes la pagina en online para verificar? o sino podrias enviarme los logs?
> Saludos
es para 1.6 o 1.7? tengo 1.6

[2021-05-12T03:48:24-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Version de Presta mayor a 1.7.0: -1
[2021-05-12T03:48:24-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Antes de llamar al formulario hibrido o externo.Valor de payment_option= form
[2021-05-12T03:48:24-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Justo antes de setear el template: payment_error
[2021-05-12T03:49:10-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Params:{"MERCHANT":"92877","OPERATIONID":"6296"}
[2021-05-12T03:49:11-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Response:{"OperationsColections":[]}
[2021-05-12T03:49:21-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Params:{"MERCHANT":"92877","OPERATIONID":"6296"}
[2021-05-12T03:49:22-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Response:{"OperationsColections":[]}
[2021-05-12T03:49:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) InitContent de Payment
[2021-05-12T03:49:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Valor de payment_option = form
[2021-05-12T03:49:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) La variable paso vale: 1
[2021-05-12T03:49:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Estás en el paso 1
[2021-05-12T03:49:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) first step
[2021-05-12T03:49:43-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) params SAR - {"comercio":{"Security":"BF5D9CEC42338C6C4388F3A16D0475B8","EncodingMethod":"XML","Merchant":"92877","URL_OK":"https:\/\/xx.com\/module\/todopago\/payment?paso=2&estado=1&cart=6454","URL_ERROR":"https:\/\/xx.com\/module\/todopago\/payment?paso=2&estado=0&cart=6454"},"operacion":{"MERCHANT":"92877","OPERATIONID":"6454","CURRENCYCODE":"032","AMOUNT":3220,"ECOMMERCENAME":"PRESTASHOP","ECOMMERCEVERSION":"1.6.1.24","PLUGINVERSION":"1.15.0-E","MAXINSTALLMENTS":"6","CSBTCITY":"caba","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":25,"CSBTIPADDRESS":"","CSBTEMAIL":"prueba123321@gmail.com","CSBTFIRSTNAME":"Seba","CSBTLASTNAME":"Dixon","CSBTPHONENUMBER":"542222222222434","CSBTPOSTALCODE":"1425","CSBTSTATE":"C","CSBTSTREET1":"dfdf","CSPTCURRENCY":"","CSPTGRANDTOTALAMOUNT":null,"CSMDD7":"1659","CSMDD10":"","CSMDD11":"542222222222434","CSMDD8":"N","CSMDD9":"ebb27b9812b8576c730ce8479490430e","CSITPRODUCTCODE":"Ra\u00edz","CSITPRODUCTDESCRIPTION":"Chaleco ","CSITPRODUCTNAME":"Camo","CSITPRODUCTSKU":"2","CSITTOTALAMOUNT":"2970.00","CSITQUANTITY":"1","CSITUNITPRICE":"2970.00","CSSTCITY":"caba","CSSTCOUNTRY":"AR","CSSTEMAIL":"sebadixon10@gmail.com","CSSTFIRSTNAME":"Seba","CSSTLASTNAME":"Dixon","CSSTPHONENUMBER":"542222222222434","CSSTPOSTALCODE":"1425","CSSTSTATE":"C","CSSTSTREET1":"dfdf","CSMDD13":"Correo Argentino a Sucursal","CSMDD12":"6","CSMDD16":""}}
[2021-05-12T03:49:44-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) response SAR - {"StatusCode":98013,"StatusMessage":"El campo CSPTCURRENCY es obligatorio. (Min Length 1)","URL_Request":"","RequestKey":"","PublicRequestKey":""}
[2021-05-12T03:49:44-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) EXCEPCION
Exception: El campo CSPTCURRENCY es obligatorio. (Min Length 1) in /home/xx/public_html/modules/todopago/controllers/front/payment.php:323
Stack trace:
#0 /home/xx/public_html/modules/todopago/controllers/front/payment.php(401): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/xx/public_html/modules/todopago/controllers/front/payment.php(113): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/xx/public_html/classes/controller/Controller.php(189): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/xx/public_html/classes/Dispatcher.php(367): ControllerCore->run()
#4 /home/xx/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}

**Comment by sebadixon** [comment]
> @sebadixon buenos dias, tenes la pagina en online para verificar? o sino podrias enviarme los logs?
> Saludos

[2021-05-12T03:48:24-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Version de Presta mayor a 1.7.0: -1
[2021-05-12T03:48:24-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Antes de llamar al formulario hibrido o externo.Valor de payment_option= form
[2021-05-12T03:48:24-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Justo antes de setear el template: payment_error
[2021-05-12T03:49:10-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Params:{"MERCHANT":"92877","OPERATIONID":"6296"}
[2021-05-12T03:49:11-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Response:{"OperationsColections":[]}
[2021-05-12T03:49:21-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Params:{"MERCHANT":"92877","OPERATIONID":"6296"}
[2021-05-12T03:49:22-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.25 - Ord.6296) GetStatus - Response:{"OperationsColections":[]}
[2021-05-12T03:49:43-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) InitContent de Payment
[2021-05-12T03:49:43-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Valor de payment_option = form
[2021-05-12T03:49:43-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) La variable paso vale: 1
[2021-05-12T03:49:43-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Estás en el paso 1
[2021-05-12T03:49:43-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) first step
[2021-05-12T03:49:43-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) params SAR - {"comercio":{"Security":"BF5D9CEC42338C6C4388F3A16D0475B8","EncodingMethod":"XML","Merchant":"92877","URL_OK":"https://xx.com/module/todopago/payment?paso=2&estado=1&cart=6454","URL_ERROR":"https://xx.com/module/todopago/payment?paso=2&estado=0&cart=6454"},"operacion":{"MERCHANT":"92877","OPERATIONID":"6454","CURRENCYCODE":"032","AMOUNT":3220,"ECOMMERCENAME":"PRESTASHOP","ECOMMERCEVERSION":"1.6.1.24","PLUGINVERSION":"1.15.0-E","MAXINSTALLMENTS":"6","CSBTCITY":"caba","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":25,"CSBTIPADDRESS":"","CSBTEMAIL":"prueba123321@gmail.com","CSBTFIRSTNAME":"Seba","CSBTLASTNAME":"Dixon","CSBTPHONENUMBER":"542222222222434","CSBTPOSTALCODE":"1425","CSBTSTATE":"C","CSBTSTREET1":"dfdf","CSPTCURRENCY":"","CSPTGRANDTOTALAMOUNT":null,"CSMDD7":"1659","CSMDD10":"","CSMDD11":"542222222222434","CSMDD8":"N","CSMDD9":"ebb27b9812b8576c730ce8479490430e","CSITPRODUCTCODE":"Ra\u00edz","CSITPRODUCTDESCRIPTION":"Chaleco ","CSITPRODUCTNAME":"Camo","CSITPRODUCTSKU":"2","CSITTOTALAMOUNT":"2970.00","CSITQUANTITY":"1","CSITUNITPRICE":"2970.00","CSSTCITY":"caba","CSSTCOUNTRY":"AR","CSSTEMAIL":"xx@gmail.com","CSSTFIRSTNAME":"Seba","CSSTLASTNAME":"Dixon","CSSTPHONENUMBER":"542222222222434","CSSTPOSTALCODE":"1425","CSSTSTATE":"C","CSSTSTREET1":"dfdf","CSMDD13":"Correo Argentino a Sucursal","CSMDD12":"6","CSMDD16":""}}
[2021-05-12T03:49:44-03:00] INFO [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) response SAR - {"StatusCode":98013,"StatusMessage":"El campo CSPTCURRENCY es obligatorio. (Min Length 1)","URL_Request":"","RequestKey":"","PublicRequestKey":""}
[2021-05-12T03:49:44-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) EXCEPCION
Exception: El campo CSPTCURRENCY es obligatorio. (Min Length 1) in /home/xx/public_html/modules/todopago/controllers/front/payment.php:323
Stack trace:
#0 /home/xx/public_html/modules/todopago/controllers/front/payment.php(401): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/xx/public_html/modules/todopago/controllers/front/payment.php(113): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/xx/public_html/classes/controller/Controller.php(189): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/xx/public_html/classes/Dispatcher.php(367): ControllerCore->run()
#4 /home/xx/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}

**Comment by curcio79** [comment]
@sebadixon veo que el campo CSPTCURRENCY  no lo esta completando, ahi veo si es algo de tu configuracion o algo del plugin. Saludos

**Comment by curcio79** [comment]
@sebadixon ahi subi una actualizacion con el campo q te solicita corregido. Si tenes otro problema no dudes en contactarme. Saludos

**Comment by sebadixon** [comment]
> @sebadixon ahi subi una actualizacion con el campo q te solicita corregido. Si tenes otro problema no dudes en contactarme. Saludos

Gracias. Otro error, igual que el anterior con respecto al front. Dejo el log.

[2021-05-20T00:52:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Version de Presta mayor a 1.7.0: -1
[2021-05-20T00:52:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Antes de llamar al formulario hibrido o externo.Valor de payment_option= form
[2021-05-20T00:52:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Justo antes de setear el template: payment_error
[2021-05-20T00:52:50-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) InitContent de Payment
[2021-05-20T00:52:50-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Valor de payment_option = form
[2021-05-20T00:52:50-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) La variable paso vale: 1
[2021-05-20T00:52:50-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Estás en el paso 1
[2021-05-20T00:52:50-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) first step
[2021-05-20T00:52:50-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) params SAR - {"comercio":{"Security":"BF5D9CEC42338C6C4388F3A16D0475B8","EncodingMethod":"XML","Merchant":"92877","URL_OK":"https:\/\/xx.com\/module\/todopago\/payment?paso=2&estado=1&cart=6454","URL_ERROR":"https:\/\/xx.com\/module\/todopago\/payment?paso=2&estado=0&cart=6454"},"operacion":{"MERCHANT":"92877","OPERATIONID":"6454","CURRENCYCODE":"032","AMOUNT":3220,"ECOMMERCENAME":"PRESTASHOP","ECOMMERCEVERSION":"1.6.1.24","PLUGINVERSION":"1.15.0-E","MAXINSTALLMENTS":"6","CSBTCITY":"caba","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":25,"CSBTIPADDRESS":"","CSBTEMAIL":"sebadixon@gmail.com","CSBTFIRSTNAME":"Seba","CSBTLASTNAME":"Dixon","CSBTPHONENUMBER":"542222222222434","CSBTPOSTALCODE":"1425","CSBTSTATE":"C","CSBTSTREET1":"dfdf","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":null,"CSMDD7":"1667","CSMDD10":"","CSMDD11":"542222222222434","CSMDD8":"N","CSMDD9":"ebb27b9812b8576c730ce8479490430e","CSITPRODUCTCODE":"Ra\u00edz","CSITPRODUCTDESCRIPTION":"Chaleco, fo","CSITPRODUCTNAME":"City Soldier","CSITPRODUCTSKU":"2","CSITTOTALAMOUNT":"2970.00","CSITQUANTITY":"1","CSITUNITPRICE":"2970.00","CSSTCITY":"caba","CSSTCOUNTRY":"AR","CSSTEMAIL":"sebadixon@gmail.com","CSSTFIRSTNAME":"Seba","CSSTLASTNAME":"Dixon","CSSTPHONENUMBER":"542222222222434","CSSTPOSTALCODE":"1425","CSSTSTATE":"C","CSSTSTREET1":"dfdf","CSMDD13":"Correo Argentino","CSMDD12":"6","CSMDD16":""}}
[2021-05-20T00:52:51-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) response SAR - {"StatusCode":98014,"StatusMessage":"El campo CSPTGRANDTOTALAMOUNT es obligatorio. (Min Length 4)","URL_Request":"","RequestKey":"","PublicRequestKey":""}
[2021-05-20T00:52:51-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) EXCEPCION
Exception: El campo CSPTGRANDTOTALAMOUNT es obligatorio. (Min Length 4) in /home/ojmb/public_html/modules/todopago/controllers/front/payment.php:323
Stack trace:
#0 /home/ojmb/public_html/modules/todopago/controllers/front/payment.php(401): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/ojmb/public_html/modules/todopago/controllers/front/payment.php(113): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/ojmb/public_html/classes/controller/Controller.php(189): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/ojmb/public_html/classes/Dispatcher.php(367): ControllerCore->run()
#4 /home/ojmb/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}
[2021-05-20T00:52:51-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Version de Presta mayor a 1.7.0: -1
[2021-05-20T00:52:51-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Antes de llamar al formulario hibrido o externo.Valor de payment_option= form
[2021-05-20T00:52:51-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.6.1.24 - Pv.1.15.0) Justo antes de setear el template: payment_error
