### ISSUE TITLE
Error al tomar datos del campo Descripción (Descripción larga)

### ISSUE THREAD

**Issue by AnibalAxA** [TodoPago/Plugin-PrestaShop#7]
Hola
Tengo problemas en múltiples productos que no los puedo vender y hoy me di cuenta que el problema es el campo (descripción).
Si en este por ejemplo tiene solo imágenes lo toma como vació y da error al querer pagar el producto (ocurrió un error)
Ver CSITPRODUCTDESCRIPTION 

Si bien hoy se cual es el error lo ideal seria solucionarlo desee el modulo de pago!
Este campo no es obligatorio y en la gran cantidad de productos es muy complejo de resolver.

Este es el log
-------------------------------------------------------------------------------------
[2016-10-12T17:55:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) first step
[2016-10-12T17:55:20-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) params SAR - {"comercio":{"Security":"xxxxxxxxxxxxxxxxxxxxx","EncodingMethod":"XML","Merchant":"11249","URL_OK":"https:\/\/www.xxx.com.ar\/web-test\/module\/todopago\/payment?paso=2&estado=1&cart=6700","URL_ERROR":"https:\/\/www.xxx.com.ar\/web-test\/module\/todopago\/payment?paso=2&estado=0&cart=6700"},"operacion":{"MERCHANT":"11249","OPERATIONID":"6700","CURRENCYCODE":"032","AMOUNT":695,"CSBTCITY":"San MIguel","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":2,"CSBTIPADDRESS":"200.5.118.115","CSBTEMAIL":"xxx@gmail.com","CSBTFIRSTNAME":"xxxxxx","CSBTLASTNAME":"xxxx","CSBTPHONENUMBER":"xxxxx","CSBTPOSTALCODE":"1663","CSBTSTATE":"B","CSBTSTREET1":"xxxx direccion","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"695.00","CSMDD7":"658","CSMDD10":"12","CSMDD11":"xxxx telefono","CSMDD8":"N","CSMDD9":"xxxxxxxx","CSITPRODUCTCODE":"default","CSITPRODUCTDESCRIPTION":"valueRAM, la memoria estndar de Kingston en este s","CSITPRODUCTNAME":"Memoria Sodimm DDR3 4GB 1333 MHZ","CSITPRODUCTSKU":"KVR13S9S8\/4","CSITTOTALAMOUNT":"695.00","CSITQUANTITY":"1","CSITUNITPRICE":"695.00","CSSTCITY":"San MIguel","CSSTCOUNTRY":"AR","CSSTEMAIL":"xxxx@
xxxx@gmail.com","CSSTFIRSTNAME":"xxx","CSSTLASTNAME":"xxxx","xxxxx":"xxxx","CSSTPOSTALCODE":"1663","CSSTSTATE":"B","CSSTSTREET1":"Concejal Tribulato 905","CSMDD13":null,"CSMDD12":"1","CSMDD16":""}}
[2016-10-12T17:55:21-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) response SAR - {"StatusCode":-1,"StatusMessage":"Solicitud de Autorizacion Registrada","URL_Request":"https:\/\/forms.todopago.com.ar\/formulario\/commands?command=formulario&m=xxxxxx","RequestKey":"xxxxxxx","PublicRequestKey":"xxxx"}
[2016-10-12T17:57:28-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) first step
[2016-10-12T17:57:28-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) params SAR - {"comercio":{"Security":"xxxx","EncodingMethod":"XML","Merchant":"11249","URL_OK":"https:\/\/www.xxx.com.ar\/web-test\/module\/todopago\/payment?paso=2&estado=1&cart=6700","URL_ERROR":"https:\/\/www.xxx.com.ar\/web-test\/module\/todopago\/payment?paso=2&estado=0&cart=6700"},"operacion":{"MERCHANT":"11249","OPERATIONID":"6700","CURRENCYCODE":"032","AMOUNT":950,"CSBTCITY":"San MIguel","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":2,"CSBTIPADDRESS":"200.5.118.115","CSBTEMAIL":"anibal.adrian@gmail.com","CSBTFIRSTNAME":"xxx","CSBTLASTNAME":"xxx","CSBTPHONENUMBER":"5491167508727","CSBTPOSTALCODE":"1663","CSBTSTATE":"B","CSBTSTREET1":"xxxx","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"950.00","CSMDD7":"658","CSMDD10":"12","CSMDD11":"5491167508727","CSMDD8":"N","CSMDD9":"xxxxxx","CSITPRODUCTCODE":"Home","CSITPRODUCTDESCRIPTION":"","CSITPRODUCTNAME":"Testeo de Prestashop","CSITPRODUCTSKU":"Teletorta","CSITTOTALAMOUNT":"950.00","CSITQUANTITY":"1","CSITUNITPRICE":"950.00","CSSTCITY":"San MIguel","CSSTCOUNTRY":"AR","CSSTEMAIL":"xxxxxx@gmail.com","CSSTFIRSTNAME":"xxx","CSSTLASTNAME":"xxx","CSSTPHONENUMBER":"xxxxxx","CSSTPOSTALCODE":"1663","CSSTSTATE":"B","CSSTSTREET1":"xxxxxx","CSMDD13":null,"CSMDD12":"1","CSMDD16":""}}
[2016-10-12T17:57:28-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) response SAR - {"StatusCode":99977,"StatusMessage":"El campo CSITPRODUCTDESCRIPTION es requerido"}
[2016-10-12T17:57:28-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.5.38 - eCv.1.6.1.7 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.2 - Ord.6700) EXCEPCION
exception 'Exception' with message 'El campo CSITPRODUCTDESCRIPTION es requerido' in /home/xxxx/public_html/web-test/modules/todopago/controllers/front/payment.php:196
Stack trace:
#0 /home/xxx/public_html/web-test/modules/todopago/controllers/front/payment.php(244): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/xxx/public_html/web-test/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/xxx/public_html/web-test/classes/controller/Controller.php(189): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/xxx/public_html/web-test/classes/Dispatcher.php(367): ControllerCore->run()
#4 /home/xxx/public_html/web-test/index.php(28): DispatcherCore->dispatch()
#5 {main}
-------------------------------------------------------------------------------------

**Comment by drarko** [comment]
Estimado,

Muchas gracias por el reporte. Lo estaremos solucionando a la brevedad. 

Saludos

**Comment by drarko** [comment]
Estimado,

¿Que version del modulo estas utilizando?
En la ultima version, este inconveniente no deberia pasar, ya que si la descripcion se encuentra vacia, se coloca el nombre del producto.

Saludos

**Comment by AnibalAxA** [comment]
Hola,

Prestashop 1.6.1.7|
Modulo TODOPAGO 1.7.1

Saludos

Anibal Adrian Vidal
AxA Computación SA
Cuit: 30-71028707-0
C. Tribulato 905, San Miguel, BA
011-4451-4283 Interno 102
anibal@axa.com.ar

**Comment by AnibalAxA** [comment]
Estimado,
El problema sucede cuando en el campo hay código HTML sin texto

Ejemplo
Contenido del campo en codigo html.

<p><img src="http://www.axa.com.ar/webaxa/img/cms/electro/batidorakitchen.jpg" alt="" width="800" height="1478" /></p>

Con este contenido da error y no deja vender el producto
Da la leyenda Ocurrio un error y no permite continuar la compra!

Saludos

**Comment by drarko** [comment]
@AnibalAxA ¿podrias probar con el ulitmo release?
Gracias

**Comment by AnibalAxA** [comment]
Hola,

Si apenas salió la 1.8.1 la instale y problema resuelto!
Un detalle menor a tener en cuenta es que reporta todavía como si fuera la version 1.7.1

Saludos
Anibal Adrian Vidal
AxA Computación SA
Cuit: 30-71028707-0
C. Tribulato 905, San Miguel, BA
011-4451-4283 Interno 102
anibal@axa.com.ar

**Comment by drarko** [comment]
Genial!
Revisamos el tema de la versión.
Saludos.
