### ISSUE TITLE
Ocurrio un error. Por favor intente nuevamente. 

### ISSUE THREAD

**Issue by alfonso100** [TodoPago/Plugin-PrestaShop#8]
estimados, cuando llego a la ventana de pago, antes de salir para TodoPago, me salta el mensaje.
 
"Ocurrió un error
Por favor intente nuevamente. "

el módulo estuvo funcionando unos días, despuís quedo asi...  no encuentro dónde puede estar el problema. 
Alguna pista?
gracias!

![image](https://cloud.githubusercontent.com/assets/229406/19699151/775d3b54-9ac8-11e6-99d4-2a76fe56e8f3.png)

**Comment by alfonso100** [comment]
este el el error log. "ERROR: El formato del campo CSBTIPADDRESS es incorrecto" 

`[2016-10-25T15:38:31-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.12 - eCv.1.6.0.9 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.365 - Ord.1724) first step
[2016-10-25T15:38:31-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.12 - eCv.1.6.0.9 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.365 - Ord.1724) params SAR - {"comercio":{"Security":"c2bf77ea645946c5976449a3cd444598","EncodingMethod":"XML","Merchant":"68387","URL_OK":"http:\/\/localhost\/cbanotebooks\/homedir\/public_html\/module\/todopago\/payment?paso=2&estado=1&cart=1724","URL_ERROR":"http:\/\/localhost\/cbanotebooks\/homedir\/public_html\/module\/todopago\/payment?paso=2&estado=0&cart=1724"},"operacion":{"MERCHANT":"68387","OPERATIONID":"1724","CURRENCYCODE":"032","AMOUNT":600,"CSBTCITY":"villa carlos paz","CSBTCOUNTRY":"AR","CSBTCUSTOMERID":365,"CSBTIPADDRESS":"::1","CSBTEMAIL":"alfonso.catron@gmail.com","CSBTFIRSTNAME":"Alfonso","CSBTLASTNAME":"Catron","CSBTPHONENUMBER":"543516111530","CSBTPOSTALCODE":"5152","CSBTSTATE":"X","CSBTSTREET1":"asuncion 150","CSPTCURRENCY":"ARS","CSPTGRANDTOTALAMOUNT":"600.00","CSMDD7":"4","CSMDD10":"0","CSMDD11":"543516111530","CSMDD8":"N","CSMDD9":"d4c52e13b51eafd11dab96f2d77f3f4d","CSITPRODUCTCODE":"Inicio","CSITPRODUCTDESCRIPTION":"Notebook Lenovo Essential Intel Celeron 28404Gb Ra","CSITPRODUCTNAME":"Lenovo Essential","CSITPRODUCTSKU":"156","CSITTOTALAMOUNT":"600.00","CSITQUANTITY":"1","CSITUNITPRICE":"600.00","CSSTCITY":"villa carlos paz","CSSTCOUNTRY":"AR","CSSTEMAIL":"alfonso.catron@gmail.com","CSSTFIRSTNAME":"Alfonso","CSSTLASTNAME":"Catron","CSSTPHONENUMBER":"543516111530","CSSTPOSTALCODE":"5152","CSSTSTATE":"X","CSSTSTREET1":"asuncion 150","CSMDD13":"C\u00f3rdoba Notebook","CSMDD12":null,"CSMDD16":""}}
[2016-10-25T15:38:31-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.12 - eCv.1.6.0.9 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.365 - Ord.1724) response SAR - {"StatusCode":98104,"StatusMessage":"ERROR: El formato del campo CSBTIPADDRESS es incorrecto"}
[2016-10-25T15:38:31-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.12 - eCv.1.6.0.9 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.365 - Ord.1724) EXCEPCION
exception 'Exception' with message 'ERROR: El formato del campo CSBTIPADDRESS es incorrecto' in /Users/alfonsocatron/moodstudio/cbanotebooks/homedir/public_html/modules/todopago/controllers/front/payment.php:196
Stack trace:
#0 /Users/alfonsocatron/moodstudio/cbanotebooks/homedir/public_html/modules/todopago/controllers/front/payment.php(244): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /Users/alfonsocatron/moodstudio/cbanotebooks/homedir/public_html/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /Users/alfonsocatron/moodstudio/cbanotebooks/homedir/public_html/classes/controller/Controller.php(180): TodoPagoPaymentModuleFrontController->initContent()
#3 /Users/alfonsocatron/moodstudio/cbanotebooks/homedir/public_html/classes/Dispatcher.php(373): ControllerCore->run()
#4 /Users/alfonsocatron/moodstudio/cbanotebooks/homedir/public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}
`

**Comment by alfonso100** [comment]
En el server de produccion los errores son diferentes:
`[2016-10-25T14:34:06-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.4.45 - eCv.1.6.0.9 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.372 - Ord.1723) response SAR - {"StatusCode":99977,"StatusMessage":"El campo CSITPRODUCTDESCRIPTION es requerido"}
`

`[2016-10-25T11:25:02-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.4.45 - eCv.1.6.0.9 - Pv.1.7.1 - EP.TODOPAGO_ENDPOINT_PROD - Cus.365 - Ord.1722) response SAR - {"StatusCode":99977,"StatusMessage":"El campo CSITPRODUCTDESCRIPTION es requerido"}
`

**Comment by drarko** [comment]
@alfonso100 
En el primer caso, para localhost, el error es de formato, el campo CSBTIPADDRESS esta enviando una dirección IPv6 (::1) y el formato aceptado es IPv4 (127.0.0.1)

En el segundo caso parece un error de formato de datos, ¿podrias enviar el log completo?
Gracias

**Comment by alfonso100** [comment]
hola drarko, gracias por tu respuesta.
si, es tal cual. El primer error era porque estaba testeando en localhost.
el segundo esta relacionado a este Issue, que ya está solucionado: 
https://github.com/TodoPago/Plugin-PrestaShop/issues/7

actualicé la version del módulo y empezó a andar perfecto.
gracias!

**Comment by Masterfarias** [comment]
Tengo la misma pantalla de error al querer comprar:
"Ocurrió un error
Por favor intente nuevamente. "
